project:
  type: website

website:
  title: "Première Analyse en Statistique Descriptive"
  navbar:
    logo: img/logo.png
    left:
      - file: intro.qmd
        text: "Introduction de l'analyse"
      - file: analyse-univarie.qmd
        text: "Analyse univariée"
      - file: analyse-bivarie.qmd
        text: "Analyse bivariée"
      - file: conclusion.qmd
        text: "Conclusion"

format:
  html:
    theme: sandstone
    toc: true
    
    
    
    # Personnalisation CSS pour le logo
include-in-header:
  - text: |
      <style>
        .navbar-logo {
          height: 80px !important;
          max-height: 80px !important;
        }
      </style>